---
abstract: 'Using TreeTagger from Perl'
author:
  - 'Aris Xanthos <aris.xanthos@unil.ch>'
build_requires:
  File::Temp: '0.19'
  Test::More: '0'
  Test::More::UTF8: '0'
configure_requires:
  File::Spec: '0'
  File::Which: '0'
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.142690'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-TreeTagger
provides:
  Lingua::TreeTagger:
    file: lib/Lingua/TreeTagger.pm
    version: '0.06'
  Lingua::TreeTagger::TaggedText:
    file: lib/Lingua/TreeTagger/TaggedText.pm
    version: '0.01'
  Lingua::TreeTagger::Token:
    file: lib/Lingua/TreeTagger/Token.pm
    version: '0.01'
requires:
  File::Temp: '0.19'
  Moose: '0'
  Path::Class: '0'
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '0.09'
